[package]
name = "op"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
is-terminal = "0.4.7"
serde = { version = "1.0.162", features = ["derive"] }
toml = "0.7.3"
